services:
  # =================================
  # 🚀 EPI Backend Web Service
  # =================================
  - type: web
    name: epi-backend
    runtime: node
    plan: free  # Change to starter/standard for production
    region: oregon  # or ohio/frankfurt depending on your location
    buildCommand: cd epi-backend && npm install --legacy-peer-deps && npx nest build && npx prisma generate
    startCommand: cd epi-backend && node dist/src/main.js
    healthCheckPath: /health
    
    # =================================
    # 🌐 Network Configuration
    # =================================
    domains:
      - epi-backend.onrender.com
    
    # =================================
    # 🏗️ Build Configuration
    # =================================
    buildFilter:
      paths:
      - epi-backend/src/**
      - epi-backend/prisma/**
      - epi-backend/package*.json
      - epi-backend/tsconfig*.json
      - epi-backend/nest-cli.json
      - epi-backend/.env.example
      ignoredPaths:
      - epi-backend/docs/**
      - epi-backend/test/**
      - "*.md"
      - .git/**
    
    # =================================
    # 🔧 Runtime Configuration
    # =================================
    rootDir: .
    
    # Auto-deploy when pushing to main
    autoDeploy: true
    branch: main
    
    # =================================
    # 📊 Environment Variables
    # =================================
    envVars:
      # Application
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      
      # Database (Render PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: epi-database
          property: connectionString
      
      # Security
      - key: JWT_SECRET
        generateValue: true  # Render will auto-generate
      - key: JWT_EXPIRES_IN
        value: "24h"
      
      # Business Configuration
      - key: PERMITIR_ESTOQUE_NEGATIVO
        value: "false"
      - key: PERMITIR_AJUSTES_FORCADOS
        value: "false"
      - key: ESTOQUE_MINIMO_EQUIPAMENTO
        value: "10"
      
      # Monitoring
      - key: LOG_LEVEL
        value: "info"
      - key: ENABLE_PERFORMANCE_MONITORING
        value: "true"
      
      # CORS
      - key: CORS_ORIGINS
        value: "https://epi-frontend.onrender.com,https://yourdomain.com"
      
      # Redis (from Redis service)
      - key: REDIS_URL
        value: "redis://default:ASlTAAIjcDE0OTNiYjI2MDQ1YWE0Y2M0OWI2NmE2MTJmOWY0M2RmOXAxMA@easy-ray-10579.upstash.io:6379"
      
      # Feature Flags
      - key: ENABLE_SWAGGER_IN_PRODUCTION
        value: "false"
      - key: ENABLE_DEBUG_LOGS
        value: "false"

  # =================================
  # 🗄️ PostgreSQL Database Service
  # =================================
databases:
  - name: epi-database
    databaseName: epi_production
    user: epi_user
    plan: free  # 1GB storage, 90 days retention
    region: oregon
    
    # Database Version
    ipAllowList: []  # Empty = allow all connections