-- CreateEnum
CREATE TYPE "categoria_epi_enum" AS ENUM ('PROTECAO_CABECA', 'PROTECAO_OLHOS_ROSTO', 'PROTECAO_OUVIDOS', 'PROTECAO_MAOS_BRACCOS', 'PROTECAO_PES', 'PROTECAO_RESPIRATORIA', 'PROTECAO_CLIMATICA', 'ROUPA_APROXIMACAO');

-- AlterTable
ALTER TABLE "tipos_epi" ADD COLUMN     "categoria" "categoria_epi_enum" NOT NULL DEFAULT 'PROTECAO_CABECA';
