export enum StatusEntrega {
  ATIVA = 'ATIVA',
  DEVOLVIDA_PARCIAL = 'DEVOLVIDA_PARCIAL',
  DEVOLVIDA_TOTAL = 'DEVOLVIDA_TOTAL',
  CANCELADA = 'CANCELADA',
}

export enum StatusEntregaItem {
  ENTREGUE = 'ENTREGUE',
  DEVOLVIDO = 'DEVOLVIDO',
  PERDIDO = 'PERDIDO',
  DANIFICADO = 'DANIFICADO',
}