export enum StatusEntrega {
  PENDENTE_ASSINATURA = 'PENDENTE_ASSINATURA',
  ASSINADA = 'ASSINADA',
  CANCELADA = 'CANCELADA',
}

export enum StatusEntregaItem {
  COM_COLABORADOR = 'COM_COLABORADOR',
  DEVOLVIDO = 'DEVOLVIDO',
}