export enum StatusEstoqueItem {
  DISPONIVEL = 'DISPONIVEL',
  AGUARDANDO_INSPECAO = 'AGUARDANDO_INSPECAO',
  DESCARTADO = 'DESCARTADO',
  RESERVADO = 'RESERVADO'
}

export enum TipoMovimentacao {
  ENTRADA = 'ENTRADA',
  SAIDA = 'SAIDA',
  TRANSFERENCIA = 'TRANSFERENCIA',
  AJUSTE_INVENTARIO = 'AJUSTE_INVENTARIO',
  DESCARTE = 'DESCARTE',
  DEVOLUCAO = 'DEVOLUCAO'
}

export enum StatusNota {
  RASCUNHO = 'RASCUNHO',
  PENDENTE = 'PENDENTE',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA'
}