export enum StatusEstoqueItem {
  DISPONIVEL = 'DISPONIVEL',
  RESERVADO = 'RESERVADO',
  AGUARDANDO_INSPECAO = 'AGUARDANDO_INSPECAO',
  DESCARTADO = 'DESCARTADO',
}

export enum TipoMovimentacao {
  ENTRADA = 'ENTRADA',
  SAIDA = 'SAIDA',
  TRANSFERENCIA = 'TRANSFERENCIA',
  AJUSTE = 'AJUSTE',
  DESCARTE = 'DESCARTE',
  ESTORNO = 'ESTORNO',
}

export enum StatusNotaMovimentacao {
  RASCUNHO = 'RASCUNHO',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
}

export enum TipoNotaMovimentacao {
  ENTRADA = 'ENTRADA',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DESCARTE = 'DESCARTE',
  AJUSTE = 'AJUSTE',
}