/**
 * Enum de Status do Estoque conforme novo schema
 * Simplificado: apenas 3 estados principais
 */
export enum StatusEstoqueItem {
  DISPONIVEL = 'DISPONIVEL',
  AGUARDANDO_INSPECAO = 'AGUARDANDO_INSPECAO',
  QUARENTENA = 'QUARENTENA',
}

/**
 * Enum de Tipos de Movimentação conforme novo schema
 * 16 valores específicos para rastreabilidade detalhada
 */
export enum TipoMovimentacao {
  ENTRADA_NOTA = 'ENTRADA_NOTA',
  SAIDA_ENTREGA = 'SAIDA_ENTREGA',
  ENTRADA_DEVOLUCAO = 'ENTRADA_DEVOLUCAO',
  SAIDA_TRANSFERENCIA = 'SAIDA_TRANSFERENCIA',
  ENTRADA_TRANSFERENCIA = 'ENTRADA_TRANSFERENCIA',
  SAIDA_DESCARTE = 'SAIDA_DESCARTE',
  AJUSTE_POSITIVO = 'AJUSTE_POSITIVO',
  AJUSTE_NEGATIVO = 'AJUSTE_NEGATIVO',
  ESTORNO_ENTRADA_NOTA = 'ESTORNO_ENTRADA_NOTA',
  ESTORNO_SAIDA_ENTREGA = 'ESTORNO_SAIDA_ENTREGA',
  ESTORNO_ENTRADA_DEVOLUCAO = 'ESTORNO_ENTRADA_DEVOLUCAO',
  ESTORNO_SAIDA_TRANSFERENCIA = 'ESTORNO_SAIDA_TRANSFERENCIA',
  ESTORNO_ENTRADA_TRANSFERENCIA = 'ESTORNO_ENTRADA_TRANSFERENCIA',
  ESTORNO_SAIDA_DESCARTE = 'ESTORNO_SAIDA_DESCARTE',
  ESTORNO_AJUSTE_POSITIVO = 'ESTORNO_AJUSTE_POSITIVO',
  ESTORNO_AJUSTE_NEGATIVO = 'ESTORNO_AJUSTE_NEGATIVO',
}

export enum StatusNotaMovimentacao {
  RASCUNHO = 'RASCUNHO',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
}

export enum TipoNotaMovimentacao {
  ENTRADA = 'ENTRADA',
  TRANSFERENCIA = 'TRANSFERENCIA',
  DESCARTE = 'DESCARTE',
  AJUSTE = 'AJUSTE',
}